%YAML 1.2
---

run: 

  engine: 'everest'
  seed: 1

  beam: '2'
  plane: 'V'
  turns: 200 #200
  nparticles: 100000 #100000 #1000
  normalized_emittance: 2.5e-6  #2.5e-6 #3.5e-6
  turn_on_cavities: True # True False 
 
  TCCS_align_angle_step:  0  #-3.370066422017441e-06 #-1.1887686184543034e-06
  TCCS_gap: 7.2 #7.2
  TARGET_gap: 33.6 #33.6
  TCCP_gap: 33.6 #33.6
  PIXEL_gap: 33.6  #33.6

  save_list: ['losses', 'TCCS_impacts', 'TARGET_impacts'] #['losses', 'TCCS_impacts', 'TARGET_impacts', 'PIXEL_impacts', 'TCP_generated']        
  target_mode: ''   #            'target_absorber' 
  input_mode: 'load'  # load  generate
  load_input_path: '/eos/home-c/cmaccani/xsuite_sim/two_cryst_sim/Condor/INPUT_PARTICLES_HL_TCP_at_6.7___20240319-0931'                                    

  
jobsubmission:
  working_directory: ${HOME_TWOCRYST}/Condor/HL_IR7_phase_
  num_jobs: 100 #5 100  
  run_local: False
  dryrun: False
  jobflavour: 'workday'  #'workday' #'espresso' testmatch
  htc_arguments: {'accounting_group': 'group_u_BE.ABP.normal', 'notification': 'never', 'MY.WantOS': '"el9"' }
  mask: ${HOME_TWOCRYST}/mask_condor_script.sh


input_files:
  #line_b2: ${HOME_TWOCRYST}/input_files/Run3_flat_top/flat_top_b2.json     
  #line_b2: ${HOME_TWOCRYST}/input_files/bkp_HL/HL_IR7_rematched/b4_sequence_patched.json
  #line_b2: ${HOME_TWOCRYST}/input_files/bkp_HL/HL_IR7_IR3_rematched/b4_sequence_patched.json
  #line_b2: ${HOME_TWOCRYST}/input_files/HL_IR7_rematched/b4_sequence_patched.json
  line_b2: ${HOME_TWOCRYST}/input_files/HL_IR7_phase_advance/b4_sequence_patched_phadv.json
  #line_b2: ${HOME_TWOCRYST}/input_files/HL_IR7_tune_changed/b4_sequence_patched_tune.json
  

  #collimators: ${HOME_TWOCRYST}/input_files/colldbs/flat_top.yaml
  collimators: ${HOME_TWOCRYST}/input_files/colldbs/HL_tight_twocryst.yaml
  #collimators: ${HOME_TWOCRYST}/input_files/colldbs/CollDB_HL_tight_b4.data







#
# IR3 IR7 rem  
# 7.200000    44.000000
# 7.700000    44.300000
# 8.200000    44.600000
# 8.700000    44.900000
#
# IR7 rem      
# 7.200000    33.600000
# 7.700000    33.900000
# 8.200000    34.300000
# 8.700000    34.600000
#