%YAML 1.2
---

run: 
  beam: '2'
  plane: 'V'
  turns: 200
  nparticles: 500000 #100000 #1000
  engine: 'everest'
  seed: 12345
  TTCS_align_angle_step: 0
  mode: 'angular_scan'   #angular_scan    cry_black_absorbers


jobsubmission:
  working_directory: '/afs/cern.ch/work/c/cmaccani/xsuite_sim/twocryst_sim/Condor/new_sim_6sig/TEST_B2V_align_test_CRY6.0_'
  num_jobs: 200 #5 100
  run_local: False
  dryrun: False
  jobflavour: 'testmatch'  #'workday' #'espresso' 
  htc_arguments: {'accounting_group': 'group_u_BE.ABP.normal', 'notification': 'never', 'MY.WantOS': '"el9"' }
  mask: '/afs/cern.ch/work/c/cmaccani/xsuite_sim/twocryst_sim/mask_condor_script.sh'


input_files:
  #line_b1: '/afs/cern.ch/work/c/cmaccani/xsuite_sim/twocryst_sim/input_files/flat_top_b1.json'
  line_b2: '/afs/cern.ch/work/c/cmaccani/xsuite_sim/twocryst_sim/input_files/flat_top_b2.json'     #flat_top/TEST_v2.json'   input_files/flat_top_b2.json
  collimators: '/afs/cern.ch/work/c/cmaccani/xsuite_sim/twocryst_sim/input_files/flat_top.yaml' 