%YAML 1.2
---

run: 
  beam: '2'
  plane: 'V'
  turns: 200 #200
  nparticles: 100000 #100000 #1000
  engine: 'everest'
  seed: 12345
  TCCS_align_angle_step: 0 #-1.1887686184543034e-06
  mode: 'target_absorber'   #angular_scan    cry_black_absorbers   monitors  xsuite  simple_model target_absorber
  normalized_emittance: 2.5e-6

jobsubmission:
  working_directory: ${HOME_TWOCRYST}/Condor/TEST_IR7rem_phadv_TCCS_7.2_
  num_jobs: 100 #5 100  
  run_local: False
  dryrun: False
  jobflavour: 'workday'  #'workday' #'espresso' testmatch
  htc_arguments: {'accounting_group': 'group_u_BE.ABP.normal', 'notification': 'never', 'MY.WantOS': '"el9"' }
  mask: ${HOME_TWOCRYST}/mask_condor_script.sh


input_files:
  #line_b1: ${HOME_TWOCRYST}/input_files/Run3_flat_top/flat_top_b1.json
  #line_b2: ${HOME_TWOCRYST}/input_files/Run3_flat_top/flat_top_b2.json     
  #line_b2: ${HOME_TWOCRYST}/input_files/bkp_HL/HL_IR7_rematched/b4_sequence_patched.json
  #line_b2: ${HOME_TWOCRYST}/input_files/bkp_HL/HL_IR7_IR3_rematched/b4_sequence_patched.json
  #line_b2: ${HOME_TWOCRYST}/input_files/HL_IR7_rematched/b4_sequence_patched.json
  line_b2: ${HOME_TWOCRYST}/input_files/HL_IR7_phase_advance/b4_sequence_patched_phadv.json
  

  #collimators: ${HOME_TWOCRYST}/input_files/colldbs/flat_top.yaml
  collimators: ${HOME_TWOCRYST}/input_files/colldbs/CollDB_HL_tight_b4.data
