%YAML 1.2
---

run: 
  beam: '2'
  plane: 'V'
  turns: 1 #200
  nparticles: 5 #100000 #1000
  engine: 'everest'
  seed: 12345
  TTCS_align_angle_step: 0
  mode: 'xsuite'   #angular_scan    cry_black_absorbers    xsuite  simple_model

jobsubmission:
  working_directory: ${HOME_TWOCRYST}/Condor/TEST_NEW_SETUP_
  num_jobs: 3 #5 100
  run_local: False
  dryrun: False
  jobflavour: 'espresso'  #'workday' #'espresso' testmatch
  htc_arguments: {'accounting_group': 'group_u_BE.ABP.normal', 'notification': 'never', 'MY.WantOS': '"el9"' }
  mask: ${HOME_TWOCRYST}/mask_condor_script.sh
  #mask: $HOME_TWOCRYST/Bjorn_model/mask_condor_script_bjorn.sh


input_files:
  #line_b1: ${HOME_TWOCRYST}/input_files/flat_top_b1.json
  #line_b2: ${HOME_TWOCRYST}/input_files/flat_top_b2.json     
  line_b2: ${HOME_TWOCRYST}/input_files/HL_IR7_rematched/b4_sequence_patched.json
  #line_b2: ${HOME_TWOCRYST}/input_files/HL_IR7_IR3_rematched/b4_sequence_patched.json
  #collimators: ${HOME_TWOCRYST}/input_files/flat_top.yaml
  collimators: ${HOME_TWOCRYST}/input_files/CollDB_HL_tight_b4.data