%YAML 1.2
---

run: 

  engine: 'everest'
  seed: 1

  beam: '2'
  plane: 'V'
  turns: 200 #200
  nparticles: 100000  #100000 #1000
  normalized_emittance: 3.5e-6  #2.5e-6 #3.5e-6
  turn_on_cavities: False # True False 
 
  TCCS_align_angle_step:  -1.7307204221061705e-06 #3.870452793781121e-06 #2.3704527937811217e-06 # 8.704527937811208e-07 #-6.295472062188801e-07  # -3.6295472062188785e-06 #-5.129547206218881e-06 #-6.62954720621888e-06 # -8.12954720621888e-06
  TCCS_gap: 5.5 #7.2
  TARGET_gap: 27.0 #33.6
  TCCP_gap:  99.9 #33.6
  PIXEL_gap: 99.9 #33.6

  save_list: ['losses', 'TCCS_impacts', 'TARGET_impacts'] #['losses', 'TCCS_impacts', 'TARGET_impacts', 'PIXEL_impacts', 'TCP_generated', TCLA_impacts, BLM_impacts]        
  target_mode: 'target_absorber'   #            'target_absorber' 
  input_mode: 'generate'  # load  generate circular_halo
  #load_input_path: '/eos/home-c/cmaccani/xsuite_sim/two_cryst_sim/Condor/INPUT_PARTICLES_HL_TCP_at_6.7___20240319-0931'   
  load_input_path: '/eos/home-c/cmaccani/xsuite_sim/two_cryst_sim/Condor/INPUT_PARTICLES_HL_TCP_at_6.7____20240319-1209'                                         

  
jobsubmission:
  working_directory: ${HOME_TWOCRYST}/Condor/RUN3_ANG_SCAN_-1.7_
  num_jobs: 100 #5 100  
  run_local: False
  dryrun: False
  jobflavour: 'workday'  #'workday' #'espresso' testmatch
  htc_arguments: {'accounting_group': 'group_u_BE.ABP.normal', 'notification': 'never', 'MY.WantOS': '"el9"', 'request_memory': '10240M'}  # 10240M 5120M
  mask: ${HOME_TWOCRYST}/mask_condor_script.sh


input_files:
  #line_b2: ${HOME_TWOCRYST}/input_files/2023_Run3_flat_top/flat_top_b2.json     
  #line_b2: ${HOME_TWOCRYST}/input_files/bkp_HL/HL_IR7_rematched/b4_sequence_patched.json
  #line_b2: ${HOME_TWOCRYST}/input_files/bkp_HL/HL_IR7_IR3_rematched/b4_sequence_patched.json
  #line_b2: ${HOME_TWOCRYST}/input_files/HL_IR7_rematched/b4_sequence_patched.json
  #line_b2: ${HOME_TWOCRYST}/input_files/HL_IR7_phase_advance/b4_sequence_patched_phadv.json
  #line_b2: ${HOME_TWOCRYST}/input_files/HL_IR7_tune_changed/b4_sequence_patched_tune.json
  #line_b2: ${HOME_TWOCRYST}/input_files/2024_Run3/injection_b2.json    # 450 GeV
  #line_b2: ${HOME_TWOCRYST}/input_files/2024_Run3/flat_top_b2.json     # 6.8 TeV
  #line_b2: ${HOME_TWOCRYST}/input_files/2024_Run3/ramp.9_b2.json        # 1 TeV
  #line_b2: ${HOME_TWOCRYST}/input_files/2024_Run3/ramp.12_b2.json     # 2 TeV
  #line_b2: ${HOME_TWOCRYST}/input_files/2024_Run3/ramp.17_b2.json      # 3 TeV



  # --------- Run3 phase scan lines ---------
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_70.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_90.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_110.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_130.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_140.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_145.json'
  line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_150.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_155.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_160.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_170.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_190.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_210.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_230.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_250.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_270.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_290.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/lines_ref/flat_top_b2_w_aper.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/lines_ref/flat_top_b2.json'

  # --------- phase scan lines ---------
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_70.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_90.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_110.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_130.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_150.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_170.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_190.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_210.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_230.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_250.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_150.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_158.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_100.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_120.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_105.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_200.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_240.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_220.json'
  #line_b2: '${HOME_TWOCRYST}/input_files/HL_phase_scan/b4_sequence_patched_phadv_270.json'
  

  collimators: ${HOME_TWOCRYST}/input_files/colldbs/flat_top.yaml  # 6.8 TeV
  #collimators: ${HOME_TWOCRYST}/input_files/colldbs/ramp.9.yaml     # 1 TeV
  #collimators: ${HOME_TWOCRYST}/input_files/colldbs/ramp.12.yaml    # 2 TeV
  #collimators: ${HOME_TWOCRYST}/input_files/colldbs/ramp.17.yaml   # 3 TeV
  #collimators: ${HOME_TWOCRYST}/input_files/colldbs/injection.yaml # 450 GeV
  #collimators: ${HOME_TWOCRYST}/input_files/colldbs/HL_tight_twocryst.yaml
  #collimators: ${HOME_TWOCRYST}/input_files/colldbs/CollDB_HL_tight_b4.data







#
# IR3 IR7 rem  
# 7.200000    44.000000
# 7.700000    44.300000
# 8.200000    44.600000
# 8.700000    44.900000
#
# IR7 rem      
# 7.200000    33.600000
# 7.700000    33.900000
# 8.200000    34.300000
# 8.700000    34.600000
#