input_files:
  collimators: /afs/cern.ch/work/c/cmaccani/xsuite_sim/twocryst_sim/input_files/flat_top.yaml
  line_b1: /afs/cern.ch/work/c/cmaccani/xsuite_sim/twocryst_sim/input_files/flat_top_b1.json
  line_b2: /afs/cern.ch/work/c/cmaccani/xsuite_sim/twocryst_sim/input_files/flat_top_b2.json
jobsubmission:
  dryrun: false
  htc_arguments:
    MY.WantOS: '"el9"'
    accounting_group: group_u_BE.ABP.normal
    notification: never
  jobflavour: workday
  mask: /afs/cern.ch/work/c/cmaccani/xsuite_sim/twocryst_sim/mask_condor_script.sh
  num_jobs: 100
  run_local: false
  working_directory: /afs/cern.ch/work/c/cmaccani/xsuite_sim/twocryst_sim/Condor/TEST_B2V_align_test_CRY6.5_-7_
run:
  TTCS_align_angle_step: -7.0e-06
  beam: '2'
  engine: everest
  nparticles: 100000
  plane: V
  seed: 12345
  turns: 200
