%YAML 1.2
---

run: 

  engine: 'everest'
  seed: 1
  fixed_seed: True

  beam: '2'
  plane: 'V'
  turns: 200 
  nparticles: 50000  #100000 #1000 50000
  normalized_emittance: 3.5e-6  
  turn_on_cavities: False 

  energy:  450e9 # 450e9 1000e9 3000e9 5000e9 6800e9 None
  adt_amplitude: None

  TCCS_potential: default # 16 default
  TCCP_potential: default # default
 
  TCCS_align_angle_step:  0 
  TCCP_align_angle_step: 0
  
  TCCS_gap: 5.0 
  TARGET_gap: None
  TCCP_gap: None
  PIXEL_gap: None
  TFT_gap: 6.4
  TCP_gap: 6.0
  TCLA_gap: 8.0 #5.0
  TCT_gap: default

  epsilon_TCCS: 0 
  epsilon_TCCP: 0
  epsilon_TARGET: 0 
  epsilon_PIXEL: 0
  epsilon_TFT: 0.6e-3
  epsilon_TCLA: 0

  save_list: ['TFT_impacts', 'losses'] #['losses', 'TCCS_impacts', 'TARGET_impacts', 'TFT_impacts','PIXEL_impacts_1', 'PIXEL_impacts_2', 'PIXEL_impacts_3', 'PIXEL_impacts_ALL',  'TCP_generated', TCLA_impacts, BLM_impacts]        
  target_mode: ''   
  input_mode: 'pencil_TCCS'  # load  pencil_TCCS  pencil_TCP circular_halo gaussian_halo
  output_mode:  '' # reduced                                  

  
jobsubmission:
  working_directory: ${HOME_TWOCRYST}/Condor/TWOCRYST_TCCS_450GeV_losses_closedTCLA
  num_jobs: 200
  angular_scan: None
  angular_scan_range_lower: 0
  angular_scan_range_upper: 0
  angular_scan_step: 0  
  run_local: False
  dryrun: False
  jobflavour: 'workday' #'espresso' testmatch
  htc_arguments: {'accounting_group': 'group_u_BE.ABP.normal', 'notification': 'never', 'MY.WantOS': '"el9"', 'request_memory': '10240M'}  
  mask: ${HOME_TWOCRYST}/mask_condor_script.sh


input_files:
  line_b2: ${HOME_TWOCRYST}/MadX/2025/injection/track_injection_b2.json
  collimators: ${HOME_TWOCRYST}/input_files/colldbs/TWOCRYST_colldb_450GeV.yaml