%YAML 1.2
---

run: 

  engine: 'everest'
  seed: 1
  fixed_seed: True

  beam: '2'
  plane: 'V'
  turns: 200 
  nparticles:  5000
  normalized_emittance: 3.5e-6  
  turn_on_cavities: False 

  energy:  None 
 
  TCCS_align_angle_step: -3.59e-06
  TCCP_align_angle_step: 0
  
  TCCS_potential: default # 16 default
  TCCP_potential: default # default

  adt_amplitude: None #0.9
  
  TCCS_gap: 5.5
  TARGET_gap: None
  TCCP_gap:  None
  PIXEL_gap: 10.0
  TFT_gap: 10.0
  TCP_gap: 5.0
  TCLA_gap: default #35.0 #9.0

  epsilon_TCCS: 0.01e-3
  epsilon_TCCP: 0
  epsilon_TARGET: 0 
  epsilon_PIXEL: 0.5e-3
  epsilon_TFT: 0.5e-3
  epsilon_TCLA: 0

  save_list: [ 'TCCS_impacts', 'PIXEL_impacts_1',  'TFT_impacts'] #['losses', 'TCCS_impacts', 'TARGET_impacts', 'TFT_impacts','PIXEL_impacts_1', 'PIXEL_impacts_2', 'PIXEL_impacts_3', 'PIXEL_impacts_ALL',  'TCP_generated', TCLA_impacts, BLM_impacts]        
  target_mode: ''           
  input_mode: 'pencil_TCP'  # load  pencil_TCCS  pencil_TCP circular_halo gaussian_halo
  output_mode: 'packed_TCCS' 
  load_input_path: '/eos/home-c/cmaccani/xsuite_sim/two_cryst_sim/Condor/INPUT_PARTICLES_HL_TCP_at_6.7____20240319-1209'                                         

  
jobsubmission:
  working_directory: ${HOME_TWOCRYST}/Condor/TWOCRYST_FLATTOP_POT_test_oldREF_
  num_jobs: 200 
  angular_scan: None
  angular_scan_range_lower: 0
  angular_scan_range_upper: 0
  angular_scan_step: 0
  run_local: False
  dryrun: False
  jobflavour: 'workday'  
  htc_arguments: {'accounting_group': 'group_u_BE.ABP.normal', 'notification': 'never', 'MY.WantOS': '"el9"'}  # 10240M 5120M , 'request_memory': '10240M'
  mask: ${HOME_TWOCRYST}/mask_condor_script.sh


input_files:
  #line_b2: ${HOME_TWOCRYST}/MadX/2025/flat_top/track_flat_top_b2.json        # 174.13306384643454
  #line_b2: ${HOME_TWOCRYST}/MadX/2025_new/flat_top/track_flat_top_b2.json   # 174.13293239423186
  
  #line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/lines_ref/flat_top_b2_w_aper.json'  #174.13293239423186
  line_b2: '${HOME_TWOCRYST}/input_files/Run3_phase_scan/flat_top_b2_phadv_150.json'  #150.18942088341294
  collimators: ${HOME_TWOCRYST}/input_files/colldbs/TWOCRYST_colldb_6.8TeV.yaml
  #collimators: ${HOME_TWOCRYST}/input_files/colldbs/tmp.yaml


#(float(tw['muy', TCCS_name])% 1* 2*np.pi - float(tw['muy', TCP_name])% 1* 2*np.pi)